server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://59.110.143.125:3306/codetool?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: dev
    password: temp01
    driver-class-name: com.mysql.jdbc.Driver